package com.jbrightman.thedayto.domain.repository

const val PREFERENCE_NAME = "THE_DAY_TO_PREF"
const val DAILY_ENTRY_CREATED = "DAILY_ENTRY_CREATED"
const val FIRST_TIME_USER = "FIRST_TIME_USER"
const val DAILY_ENTRY_DATE = "DAILY_ENTRY_DATE"
const val NOTIFICATIONS_ALLOWED = "NOTIFICATIONS_ALLOWED"
